version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: xeno_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
   
    networks:
      - xeno_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: xeno_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - xeno_network

  redis:
    image: redis:latest
    container_name: xeno_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - xeno_network

volumes:
  mongodb_data:
  redis_data:
  rabbitmq_data:

networks:
  xeno_network:
    driver: bridge 